spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 5000ms
  session:
    store-type: redis
    timeout: 1800s
server:
  servlet:
    session:
      cookie:
        secure: false  # HTTP 환경에서는 false, HTTPS에서는 true
        http-only: true
        same-site: None
